[package]
name = "loxide"
version = "0.1.0"
edition = "2021"

[features]
vm_debug_trace = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
